"""add processed_events

Revision ID: 4db31a374f64
Revises: cb4d03f5ba51
Create Date: 2026-09-28 13:09:25.968169
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4db31a374f64'
down_revision: str | None = 'cb4d03f5ba51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_events')),
    sa.UniqueConstraint('event_id', 'consumer_name', name='uq_processed_events_event_consumer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    # ### end Alembic commands ###
