"""create meeting

Revision ID: 73b5a700d3a5
Revises: eb30b7b81b98
Create Date: 2026-09-24 16:37:22.072839
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '73b5a700d3a5'
down_revision: str | None = 'eb30b7b81b98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'FAILED', name='meetingstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_meetings_client_id_clients')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meetings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    op.create_index(op.f('ix_meetings_client_id'), 'meetings', ['client_id'], unique=False)
    op.create_index(op.f('ix_meetings_tenant_id'), 'meetings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_tenant_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_client_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
