"""add meeting analysis and intelligence tables

Revision ID: e85a5cbb6d2e
Revises: 73b5a700d3a5
Create Date: 2026-09-28 11:48:04.167599
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e85a5cbb6d2e'
down_revision: str | None = '73b5a700d3a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_action_items_client_id_clients')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_action_items_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_action_items_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    op.create_index(op.f('ix_action_items_client_id'), 'action_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_tenant_id'), 'action_items', ['tenant_id'], unique=False)
    op.create_table('client_concerns',
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_concerns_client_id_clients')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_client_concerns_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_client_concerns_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_concerns'))
    )
    op.create_index(op.f('ix_client_concerns_client_id'), 'client_concerns', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_concerns_meeting_id'), 'client_concerns', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_client_concerns_tenant_id'), 'client_concerns', ['tenant_id'], unique=False)
    op.create_table('client_goals',
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('timeframe', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_goals_client_id_clients')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_client_goals_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_client_goals_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_goals'))
    )
    op.create_index(op.f('ix_client_goals_client_id'), 'client_goals', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_goals_meeting_id'), 'client_goals', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_client_goals_tenant_id'), 'client_goals', ['tenant_id'], unique=False)
    op.create_table('life_events',
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_life_events_client_id_clients')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_life_events_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_life_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_events'))
    )
    op.create_index(op.f('ix_life_events_client_id'), 'life_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_life_events_meeting_id'), 'life_events', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_life_events_tenant_id'), 'life_events', ['tenant_id'], unique=False)
    op.create_table('meeting_topics',
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_meeting_topics_client_id_clients')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_topics_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_topics_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_topics'))
    )
    op.create_index(op.f('ix_meeting_topics_client_id'), 'meeting_topics', ['client_id'], unique=False)
    op.create_index(op.f('ix_meeting_topics_meeting_id'), 'meeting_topics', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_topics_tenant_id'), 'meeting_topics', ['tenant_id'], unique=False)
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('meetings', sa.Column('model_version', sa.String(length=100), nullable=True))
    op.add_column('meetings', sa.Column('prompt_version', sa.String(length=100), nullable=True))
    op.add_column('meetings', sa.Column('processing_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'processing_timestamp')
    op.drop_column('meetings', 'prompt_version')
    op.drop_column('meetings', 'model_version')
    op.drop_column('meetings', 'model')
    op.drop_column('meetings', 'summary')
    op.drop_index(op.f('ix_meeting_topics_tenant_id'), table_name='meeting_topics')
    op.drop_index(op.f('ix_meeting_topics_meeting_id'), table_name='meeting_topics')
    op.drop_index(op.f('ix_meeting_topics_client_id'), table_name='meeting_topics')
    op.drop_table('meeting_topics')
    op.drop_index(op.f('ix_life_events_tenant_id'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_meeting_id'), table_name='life_events')
    op.drop_index(op.f('ix_life_events_client_id'), table_name='life_events')
    op.drop_table('life_events')
    op.drop_index(op.f('ix_client_goals_tenant_id'), table_name='client_goals')
    op.drop_index(op.f('ix_client_goals_meeting_id'), table_name='client_goals')
    op.drop_index(op.f('ix_client_goals_client_id'), table_name='client_goals')
    op.drop_table('client_goals')
    op.drop_index(op.f('ix_client_concerns_tenant_id'), table_name='client_concerns')
    op.drop_index(op.f('ix_client_concerns_meeting_id'), table_name='client_concerns')
    op.drop_index(op.f('ix_client_concerns_client_id'), table_name='client_concerns')
    op.drop_table('client_concerns')
    op.drop_index(op.f('ix_action_items_tenant_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_client_id'), table_name='action_items')
    op.drop_table('action_items')
    # ### end Alembic commands ###
