"""add tenant slug

Revision ID: eb30b7b81b98
Revises: c7454ec2ed3f
Create Date: 2026-09-24 14:30:00.331449
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eb30b7b81b98'
down_revision: str | None = 'c7454ec2ed3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###
